version: "3"

env:
  IMAGE_NAME: gcr.io/modular-monolith-sample/app
  SERVICE_NAME: modular-monolith
  REGION: asia-northeast1

tasks:
  build-callanotherapi-micro:
    cmds:
      - cmd: go build -tags=micro -o ./bin/callanotherapi_micro ./services/callanotherapi/main.go
        dir: .
    silent: false

  build-callanotherapi-mono:
    cmds:
      - cmd: go build -tags=mono -o ./bin/callanotherapi_mono ./services/callanotherapi/main.go
        dir: .
    silent: false

  build-healthcheck:
    cmds:
      - cmd: go build -o ./bin/healthcheck ./services/healthcheck/main.go
        dir: .
    silent: false

  build-monoapp:
    cmds:
      - cmd: go build -o ./bin/monoapp ./main.go
        dir: .
    silent: false

  build-micro-app:
    cmds:
      - task: build-callanotherapi-micro
      - task: build-healthcheck

  docker-build:
    cmds:
      - cmd: docker build -t $IMAGE_NAME:latest .

  docker-push:
    cmds:
      - cmd: docker push $IMAGE_NAME:latest

  deploy-to-cloud-run:
    cmds:
      - cmd: gcloud run deploy $SERVICE_NAME --image $IMAGE_NAME:latest --platform managed --region $REGION --allow-unauthenticated

  build-and-deploy:
    desc: Build, Push and Deploy to Cloud Run
    cmds:
      - task: docker-build
      - task: docker-push
      - task: deploy-to-cloud-run

  delete:
    cmds:
      - cmd: gcloud run services delete $SERVICE_NAME --region asia-northeast1 --platform managed
