version: "3"

env:
  IMAGE_NAME: gcr.io/modular-monolith-sample/fileservice/app
  SERVICE_NAME: fileservice
  REGION: asia-northeast1

tasks:
  build-fileservice:
    cmds:
      - cmd: go build -o ./bin/fileservice ./services/fileservice/main.go
        dir: .
    silent: false

  docker-build:
    cmds:
      - cmd: docker build -t $IMAGE_NAME:latest -f Dockerfile ../..

  docker-push:
    cmds:
      - cmd: docker push $IMAGE_NAME:latest

  deploy-to-cloud-run:
    dir: ../../infrastructure/envs
    cmds:
      - cmd: cdktf deploy --auto-approve

  plan:
    dir: ../../infrastructure/envs
    cmds:
      - cmd: cdktf plan

  build-and-deploy:
    desc: Build, Push and Deploy to Cloud Run
    cmds:
      - task: docker-build
      - task: docker-push
      - task: deploy-to-cloud-run

  delete:
    dir: ../../infrastructure/envs
    cmds:
      - cmd: cdktf destroy --auto-approve
