version: "3"

env:
  IMAGE_NAME: gcr.io/modular-monolith-sample/fileservice/app
  SERVICE_NAME: fileservice
  REGION: asia-northeast1

tasks:
  build-fileservice:
    cmds:
      - cmd: go build -o ./bin/fileservice ./services/fileservice/main.go
        dir: .
    silent: false

  docker-build:
    cmds:
      - cmd: docker build -t $IMAGE_NAME:latest -f Dockerfile ../..

  docker-push:
    cmds:
      - cmd: docker push $IMAGE_NAME:latest

  deploy-to-cloud-run:
    cmds:
      - cmd: gcloud run deploy $SERVICE_NAME --image $IMAGE_NAME:latest --platform managed --region $REGION --allow-unauthenticated

  build-and-deploy:
    desc: Build, Push and Deploy to Cloud Run
    cmds:
      - task: docker-build
      - task: docker-push
      - task: deploy-to-cloud-run

  delete:
    cmds:
      - cmd: gcloud run services delete $SERVICE_NAME --region asia-northeast1 --platform managed
