name: Continuous Integration
on:
  push:
    tags:
      - v*
    branches-ignore:
      - main
permissions:
  contents: read
jobs:
  trigger_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.work
      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.work.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run golangci lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56.2
          args: --config=.golangci.yml ./pkg/... ./services/intermediary/... ./services/healthcheck/...
      - name: Run hadolint
        uses: brpaz/hadolint-action@master
      - name: Run test
        run: |
          go test ./pkg/... ./services/intermediary/... ./services/healthcheck/...
      - name: Run hadolint
        uses: hadolint/hadolint-action@master
        with:
          recursive: true
